### ISSUE TITLE
EmployerType interface should include an enum not string

### ISSUE THREAD

**Issue by wozzer72** [NMDSdevopsServiceAdm/SopraSteria-SFC#120]
The employer type is a fixed set of types. Better implemented as a type safe enum than a string: src/app/core/services/establishment.service.ts .

Also, the postEmployerType should typecast to an EmployerTypeRequest interface definition.

**Comment by adamfaryna** [comment]
> The employer type is a fixed set of types. Better implemented as a type safe enum than a string: src/app/core/services/establishment.service.ts .
> 
> Also, the postEmployerType should typecast to an EmployerTypeRequest interface definition.

Which lines of code does it relates to?
